Repository bigscience-workshop/evaluation, pull requests merged in 2021-08, with the labels that each got.

#44 Add TyDi QA to Simple Benchmark
  .gitignore
  README.md
  evaluation/datasets/tydiqa.py
  evaluation/scripts/simple_benchmark.py
  evaluation/utils/__init__.py
  evaluation/utils/io.py
  requirements.txt
Labels: simple_benchmark

#52 Refactor overall directory structure
  README.md
  evaluation/eval.py
  evaluation/scripts/simple_benchmark.py
  evaluation/tasks/__init__.py
  evaluation/tasks/auto_task.py
  evaluation/tasks/tydiqa_primary/__init__.py
  evaluation/tasks/tydiqa_primary/tydiqa_primary.py
  evaluation/tasks/tydiqa_secondary/__init__.py
  evaluation/tasks/tydiqa_secondary/tydiqa_secondary.py
  evaluation/tasks/wmt/wmt.py
  evaluation/utils/log.py
Labels: engineering

#59 Add PIQA dataset
  evaluation/tasks/piqa/__init__.py
  evaluation/tasks/piqa/english.json
  evaluation/tasks/piqa/piqa.py
Labels: simple_benchmark

#58 Add WMT dataset
  evaluation/tasks/wmt/__init__.py
  evaluation/tasks/wmt/english.json
  evaluation/tasks/wmt/wmt.py
Labels: simple_benchmark

#60 Add basic template
  evaluation/tasks/template/__init__.py
  evaluation/tasks/template/english.json
  evaluation/tasks/template/multilingual.json
  evaluation/tasks/template/template.py
Labels: enhancement
